### ISSUE TITLE
Anthello147: PostmarketOS for Lumia 630

### ISSUE THREAD

**Issue by FieryFlames** [taskcollect/ap-taskcollect#1] opened 2021-11-05 01:33 UTC
Hi, I saw you have attempted to get PostmarketOS onto a Lumia630 in the past.
Some recent development actually makes it possible to do that, could you please contact me on one of the following platforms:
Discord: Fiery#9119
Telegram: FieryFlames or https://t.me/mainline4lumia

**Comment by xxori** [comment] 2021-11-05 03:31
not funny

**Comment by xxori** [comment] 2021-11-05 03:31
duplicate of #54

**Comment by xxori** [comment] 2021-11-05 03:32
please consult sugma for further information

**Closed by xxori** 2021-11-05 03:31 UTC

**Comment by FieryFlames** [comment] 2021-11-05 04:18
not funny didn't laugh

**Comment by anthello147** [comment] 2021-11-05 04:22
> Hi, I saw you have attempted to get PostmarketOS onto a Lumia630 in the past. Some recent development actually makes it possible to do that, could you please contact me on one of the following platforms: Discord: Fiery#9119 Telegram: FieryFlames or https://t.me/mainline4lumia

Hello.

Please be aware that this repository is not a suitable place for communication for topics not directly related to matters regarding the software in the repository.

That being said, I understand I have not provided information on how to contact me for discussing pmOS, so apologies for that. I am currently a bit busy at the moment; I will try to get back to you in a couple of days.

I saw your repository with the EDK2 port for the Lumia 630. Is that what you were referring to when you meant "recent development"? Also, feel free to take over the porting effort for pmOS on the Lumia 630 , you probably have more expertise on the matter. I don't really have any experience in porting, and I'm probably not going to have much time available for getting Linux on the Lumia.

**Comment by FieryFlames** [comment] 2021-11-05 04:26
> Please be aware that this repository is not a suitable place for communication for topics not directly related to matters regarding the software in the repository.
> 
Sorry for using this gh repo, wasn't able to find any way to contact you as you said. 

> I saw your repository with the EDK2 port for the Lumia 630. Is that what you were referring to when you meant "recent development"? Also, feel free to take over the porting effort for pmOS on the Lumia 630 , you probably have more expertise on the matter. I don't really have any experience in porting, and I'm probably not going to have much time available for getting Linux on the Lumia.

Yes, the recent development is that we can now boot postmarketOS through EDK2
If you're 100% okay with me taking over porting it, I would be happy to do that.

**Comment by anthello147** [comment] 2021-11-05 04:32
Yes, I'm 100% okay with that.

**Comment by FieryFlames** [comment] 2021-11-05 04:37
Alright cool, thank you!

**Comment by xxori** [comment] 2021-11-05 04:43
sorry for posting that sugma stuff i really didnt mean it

**Comment by FieryFlames** [comment] 2021-11-05 04:58
sounds like you had a case of ligma
